language: csharp  
sudo: required  
dist: trusty  
mono: none
dotnet: 2.0.0
repo_token: 3zOe5ZP6VEDvIrQtVguCG5eDGBa6oQxlu
before_script:
  - dotnet restore
script:  
  - dotnet test ./UnitTestLoggers -c Release -f netcoreapp2.0
